CREATE TABLE IF NOT EXISTS QUESTION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    QUESTION TEXT NOT NULL,
    ALTERNATIVE_A TEXT NOT NULL,
    ALTERNATIVE_B TEXT NOT NULL,
    ALTERNATIVE_C TEXT NOT NULL,
    ALTERNATIVE_D TEXT NOT NULL,
    ANSWER VARCHAR(1) NOT NULL,
    AMOUNT INT NOT NULL,
    THEME VARCHAR(250),
    TIMETOANSWER INT DEFAULT 60
);
